spring:
  mail:
    host: smtp.gmail.com
    username: 'fabio.avasc@gmail.com'
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true

