spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: 'root'
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup

io:
  reflectoring:
    kafka:
      bootstrap-servers: localhost:9092
      topic-1: reflectoring-1